### ISSUE TITLE
Pouvoir supprimer un enrollement

### ISSUE THREAD

**Issue by annemarie35** [betagouv/signup.api.gouv.fr#127]
ETQ usager fournisseur de service, je peux supprimer une demande si elle n'a pas encore été transmise (si elle est `pending`).

ETQ validateur, je ne peux pas supprimer une demande, mais je peux les archiver

**Comment by Flightan** [comment]
Je pense que c'est une bonne fonctionnalité pour l'utilisateur (ex: j'ai créé une demande en doublon par erreur).
Mais ça ne devrait pas être possible pour un gérant (API part/entreprise/dgfip).

Donc selon moi:
ETQ usager fournisseur de service, je peux supprimer une demande si elle n'a pas encore été transmise (si elle est `pending`).
