### ISSUE TITLE
Enlever le .env quand on aura des variables d'environnements et un serveur

### ISSUE THREAD

**Issue by annemarie35** [betagouv/signup.api.gouv.fr#40]
Pour le moment on utilise gh-pages et on est obligé de commiter le .env
Penser à le passer dans le .gitignore plus tard

**Comment by pknoth** [comment]
le front étant une SPA, je ne pense pas qu'il soit nécessaire de cacher des variables d'environnement. Par contre il sera nécessaire de créer un nouveau client oauth, l'actuel étant visible dans les seeds de api-particulier-courtier-oauth
