### ISSUE TITLE
L'embed runkit est importé plusieurs fois

### ISSUE THREAD

**Issue by Flightan** [betagouv/signup.api.gouv.fr#66]
`data-set-description.js` est utilisé plusieurs fois (1x par jeu de données), à chaque fois il ajoute:
```
<Head>
<script src='https://embed.runkit.com'></script>
</Head>
```

<img width="684" alt="screen shot 2018-03-29 at 10 39 11" src="https://user-images.githubusercontent.com/1475946/38078735-8112eebe-333d-11e8-93c0-4e993e98fcc7.png">

**Comment by pknoth** [comment]
je vois pas trop la solution... tu as des idées ? je pensais à l'inclure dans index.js

**Comment by Flightan** [comment]
Oui `index.js` peut faire l'affaire.
